nombres_m= ["Juan", "Pedro", "Luis", "Carlos", "Martin", "Diego", "Gustavo", "Jose", "Mario", "Gonzalo", "Jorge"]
nombres_f = ["Maria", "Ana", "Laura", "Carmen", "Sofia", "Luisa", "Carmen", "Valentina", "Sonia", "Roxana", "Rocio"]
apellidos_data = ["García", "Martínez", "Rodriguez", "Pérez", "López", "Gonzalez", "Vasquez", "Gimenez", "Alvarez", "Marquez"]
localidades_data = ["Avellaneda", "Quilmes", "Bernal", "Lanus", "Temperley", "Wilde", "Sarandi", "Hudson", "Berazategui", "Lomas"]
provincias_data = ["Buenos Aires", "Córdoba", "Santa Fe", "Mendoza", "Buenos Aires", "Corrientes", "Entre Rios", "Misiones", "Neuquen"]
sectores_data = ["Contabilidad", "RRHH", "Compras", "Ventas", "Sistemas", "Legales", "Marketing", "Gerencia"]
dominios_data = ["@empresa.com", "@corporacion.com", "@negocios.com", "@gmail.com", "@yahoo.com", "@hotmail.com"]
