
nombres = ["Juan", "María", "Luis", "Ana", "Pedro", "Laura", "Carlos", "Sofía", "Miguel", "Lucía", "José", "Elena", "David", "Isabel", "Fernando", "Paula", "Pablo", "Carmen", "Javier", "Teresa", "Raúl", "Beatriz", "Alejandro", "Silvia", "Daniel",
"Eva", "Adrián", "Clara", "Jorge", "Natalia", "Rubén", "Patricia", "Alberto", "Martina", "Diego", "Verónica", "Roberto", "Raquel", "Francisco", "Rocío", "Ricardo", "Julia", "Joaquín", "Cristina", "Antonio", "Lorena", "Manuel", "Virginia"]

apellidos = ["García", "Rodríguez", "López", "Martínez", "Hernández", "González", "Pérez", "Sánchez", "Ramírez", "Torres", "Flores", "Díaz", "Vázquez", "Romero", "Álvarez", "Ruiz", "Jiménez", "Moreno", "Molina", "Ortega", "Navarro", "Gutiérrez", "Serrano",
"Ortiz", "Delgado", "Castro", "Suárez", "Cruz", "Morales", "Iglesias", "Gómez", "Vega", "Fernández", "Rojas", "Reyes", "Blanco", "Núñez", "Medina", "Guerrero", "Santos", "Gálvez", "Herrera", "Méndez", "Aguilar", "Marín", "Peña", "Carmona", "Santiago"]

generos = ["f", "f", "m", "f", "m", "f", "m", "f", "m", "f", "m", "f", "m", "f", "m", "f", "m", "f", "m", "f", "m", "f", "m", "f", "m", "f", "m", "f", "m", "f", "m", "f", "m", "f", "m", "f", "m", "f", "m", "f", "m", "f", "m", "f", "m", "f", "m", "f", "m"]

emails = ["juan.garcia@gmail.com", "maria.rodriguez@hotmail.com", "luis.lopez@yahoo.com", "ana.martinez@gmail.com", "pedro.hernandez@hotmail.com", "laura.gonzalez@yahoo.com", "carlos.perez@gmail.com", "sofia.sanchez@hotmail.com", "miguel.ramirez@yahoo.com", "lucia.torres@gmail.com", "jose.flores@hotmail.com", "elena.diaz@yahoo.com", "david.vazquez@gmail.com", "isabel.romero@hotmail.com", "fernando.alvarez@yahoo.com", "paula.ruiz@gmail.com", "pablo.jimenez@hotmail.com", "carmen.moreno@yahoo.com", "javier.molina@gmail.com", "teresa.ortega@hotmail.com", "raul.navarro@yahoo.com", "beatriz.gutierrez@gmail.com", "alejandro.serrano@hotmail.com", "silvia.ortiz@yahoo.com","daniel.delgado@gmail.com", "eva.castro@hotmail.com", "adrian.suarez@yahoo.com", "clara.ruz@gmail.com", "jorge.morales@hotmail.com", "natalia.iglesias@yahoo.com", "ruben.gomez@gmail.com", "patricia.vega@hotmail.com", "alberto.fernandez@yahoo.com", "martina.rojas@gmail.com", "diego.reyes@hotmail.com", "veronica.blanco@yahoo.com", "roberto.nunez@gmail.com", "raquel.medina@hotmail.com", "francisco.guerrero@yahoo.com", "rocio.santos@gmail.com", "ricardo.galvez@hotmail.com", "julia.herrera@yahoo.com", "joaquin.mendez@gmail.com", "cristina.aguilar@hotmail.com", "antonio.marin@yahoo.com", "lorena.pena@gmail.com", "manuel.carmona@hotmail.com", "virginia.santiago@yahoo.com"]
